### PR TITLE
Handle gappy state with a single snapshot, attempt 3

### LINKED ISSUE #232: Checkpoint room state
Users can join and leave rooms. If all users who are using the proxy leave a room, then Stuff happens and someone rejoins, the poller will be resent the _entire room state from fresh_. We currently do not use this correctly, and instead treat it as a "gappy sync", meaning we take what we previously had as the room state, and "roll forward" using what we are told in the state block.

We shouldn't do that, as it means that we can't handle state resets correctly (i.e we never remove state by rolling forwards), and if we calculate the wrong state in the past (not uncommon), we cannot self-heal by using the latest authoritative answer from upstream.

To do this is reasonably easy. All we need to do is, in `Initialise`:
 - is there an `m.room.create` even in the `state` block?
    * No: gappy sync, roll forward.
    * Yes: this sync contains everything, do a complete snapshot "rolling forwards" from the empty set [].

### LINKED ISSUE #294: Cache invalidation
### Cache invalidation in SS

This is the process of informing downstream API caches that what they have remembered for a room is incorrect and needs refetching from the database. We (dmr & kegan) propose invalidation is room ID scoped, and not more fine-grained for now. This keeps things simple but means we ask the DB for more information than we strictly need to.

Cases when invalidation are needed:
 - Redactions. Whilst the proxy doesn't cache the event content of messages, it definitely does cache things like the room name. If the room name is redacted, we need to inform the global/user/connection caches that the name is now unset. This also applies to member display names (for `room.name`) and avatar URLs (for `room.avatar`), as well as the canonical alias (for `room.name`).
 - State resolution. This is part of a broader strategy for refreshing entire room state snapshots. The downstream room state caches are currently loaded on startup then strictly updated when _live timeline events_ arrive from the poller. This is a problem when:
     * the state changes without a timeline event (state resets),
	 * the proxy has a very old copy of a room which is updated when a poller joins that room.

   In the latter case, we fudged a solution by incorrectly prepending `state` block events to the timeline to get the caches to update downstream correctly. This makes the timeline incorrect when the client asks for a sufficiently high `timeline_limit` though.

We propose to add a new payload type `V2InvalidateRoom` which will contain the room ID to invalidate and the new snapshot ID to load from. This will cause downstream API processes to reload caches from that snapshot. The precise data that needs to be reloaded is the entire list of all joined members and invited members in addition to populating this struct:

```go
type RoomMetadata struct {
	RoomID         string
	Heroes         []Hero
	NameEvent      string // the content of m.room.name, NOT the calculated name
	AvatarEvent    string // the content of m.room.avatar, NOT the resolved avatar
	CanonicalAlias string
	JoinCount      int
	InviteCount    int
	// LastMessageTimestamp is the origin_server_ts of the event most recently seen in
	// this room. Because events arrive at the upstream homeserver out-of-order (and
	// because origin_server_ts is an untrusted event field), this timestamp can
	// _decrease_ as new events come in.
	LastMessageTimestamp uint64
	// LatestEventsByType tracks timing information for the latest event in the room,
	// grouped by event type.
	LatestEventsByType map[string]EventMetadata
	Encrypted          bool
	PredecessorRoomID  *string
	UpgradedRoomID     *string
	RoomType           *string
	// if this room is a space, which rooms are m.space.child state events. This is the same for all users hence is global.
	ChildSpaceRooms map[string]struct{}
	// The latest m.typing ephemeral event for this room.
	TypingEvent json.RawMessage
}
```

For redactions, we strictly only need `Heroes`, `NameEvent`, `AvatarEvent`, `CanonicalAlias` as they contain redactable user input.

For state resets, we need all state related fields. This is all fields with the exception of `LatestEventsByType`, `LastMessageTimestamp` and `TypingEvent`, though in practice in most cases we would have a new latest event in the room, and the typing event would be nullified as too old.

Even if we populate downstream caches effectively, we need to _communicate this information to the client_. The room list sorting logic assumes 1 update affects at most 1 room and therefore causes at most 0-1 move operations. In the invalidation scenario, this assumption holds if we invalidate 1 room per payload. This also matches reality well as often we are talking about a single room being joined, redacted or state reset, not many. In theory, it should be enough to just send an update to connections with the newly updated `RoomConnMetadata` values and have it do the right thing, but code will need to be checked to not assume that only 1 action can take place per payload (e.g it is possible for the room name to change AND space children to change AND typing to change, etc). We probably also need to resend any `required_state` events with their new values. E.g if `m.room.name` was requested and we just redacted it, we should resend it with `content: {}`. 

Testing wise, we need to engineer several failure scenarios:
 - Redactions: Room with name + canonical alias. Redact room name => `room.name` updates to canonical alias.
 - Gappy state: whilst sync v2 is not capable of expressing state resets, we can inject gappy state responses which roughly mimic this. For this, send 5 msgs, then send a gappy state response (room name state event in the state block, setting limited: true, and sending a single latest timeline event with a prev_batch token). Then do a sync for timeline_limit: 20. We should only get 1 event, the latest event, the correct prev_batch token and the correct updated room name.

Redactions work was done in https://github.com/matrix-org/sliding-sync/pull/296.

 Detecting cache invalidation in pollers:
  - whenever a timeline response is `limited` and `timeline[0]` is unknown, then we don't know if `timeline[-1]` is known or unknown, so cannot safely respond to `timeline_limit`s which span these events. We should "invalidate" the timeline to only return the span we know to be safe (the latest response). We do not store timelines in-memory, so the invalidation is purely database-backed (probably via a flag on the event row itself). 
    - Issue: https://github.com/matrix-org/sliding-sync/issues/283
    - Fix: #300
  - whenever there are events in the `state` block for a room, and we don't know some of them (i.e prepend state events logic). At this point, we should make a new snapshot and invalidate caches downstream.
    -  Issue: Making the snapshot fixes https://github.com/matrix-org/sliding-sync/issues/232 and obviates the need to do https://github.com/matrix-org/sliding-sync/issues/270 (unless we want to do the latter for storage space reasons).
    - Fix: TBD
  - NOTE: these 2 points are often correlated but not always e.g send 1000 messages = limited: true but no state block.

### PR DESCRIPTION
**Pull request by DMRobertson**
A third iteration of "deal with the gappy poll problem".

I pulled out all the independent bits from #329 to other PRs. What was left fell into two categories: a) the original logic for trying to push out live updates with the gappy poll changes; and b) the logic for nuking connections. This PR consists of b) but not a).

Ancestry: #310 -> #329 -> this.
Closes #294.
Closes #232.

### CODE REVIEW

File: state/accumulator.go [hunk 1]
```diff
@@ -214,77 +207,76 @@ func (a *Accumulator) Initialise(roomID string, state []json.RawMessage) (Initia
...
+		var currentState stateMap
+		if startingSnapshotID > 0 {
+			currentState, err = a.stateMapAtSnapshot(txn, startingSnapshotID)
+			if err != nil {
+				return fmt.Errorf("failed to load state map: %w", err)
+			}
+		} else {
+			currentState = stateMap{
+				Memberships: make(map[string]int64, len(events)),
+				Other:       make(map[[2]string]int64, len(events)),
```
Comment (kegsay) [inline state/accumulator.go:259]: This will nearly always be way too large as membership events >>>> other events, I'd just leave memberships with `len(events)` and let `Other` self-size.

File: sync2/handler2/handler.go [hunk 2]
```diff
@@ -370,20 +370,24 @@ func (h *Handler) Accumulate(ctx context.Context, userID, deviceID, roomID strin
...
 		internal.GetSentryHubFromContextOrDefault(ctx).CaptureException(err)
-		return nil, err
+		return err
 	}
-	if res.AddedEvents {
+	if res.ReplacedExistingSnapshot {
+		h.v2Pub.Notify(pubsub.ChanV2, &pubsub.V2InvalidateRoom{
+			RoomID: roomID,
+		})
+	} else if res.AddedEvents {
```
Comment (kegsay) [inline sync2/handler2/handler.go:384]: Are they mutally exclusive? If so, an enum would be better than 2 bools.

File: sync3/handler/handler.go [hunk 3]
```diff
@@ -818,7 +834,46 @@ func (h *SyncLiveHandler) OnInvalidateRoom(p *pubsub.V2InvalidateRoom) {
...
+		hub.WithScope(func(scope *sentry.Scope) {
+			scope.SetContext(internal.SentryCtxKey, map[string]any{
+				"room_id": p.RoomID,
+			})
+			hub.CaptureException(err)
+		})
+		logger.Err(err).
+			Str("room_id", p.RoomID).
+			Msg("Failed to fetch members after cache invalidation")
+	}
```
Comment (kegsay) [inline sync3/handler/handler.go:859]: Unclear if fall through is intentional here. Comment or `return` please.

File: sync3/handler/handler.go [hunk 4]
```diff
@@ -818,7 +834,46 @@ func (h *SyncLiveHandler) OnInvalidateRoom(p *pubsub.V2InvalidateRoom) {
...
+
+	h.Dispatcher.OnInvalidateRoom(p.RoomID, joins, invites)
+
+	// 3. Destroy involved users' caches.
+	for _, userID := range involvedUsers {
```
Comment (kegsay) [inline sync3/handler/handler.go:864]: `involvedUsers` is potentially very large (think Matrix HQ). It would be better to cut this down to the connected users first, then continue. Otherwise we will spin a lot of cycles/locks on users not even on the upstream HS...

**Review by kegsay — APPROVED** [review]

File: state/accumulator.go (hunk 1 above)
Comment (DMRobertson) [reply state/accumulator.go]: 9ad93b8

File: sync3/handler/handler.go (hunk 3 above)
Comment (DMRobertson) [reply sync3/handler/handler.go:859]: Unintentional. 041965f

File: sync3/handler/handler.go (hunk 4 above)
Comment (DMRobertson) [reply sync3/handler/handler.go:865]: > It would be better to cut this down to the connected users first, then continue.

Does this run the risk of introducing a race?

File: sync2/handler2/handler.go (hunk 2 above)
Comment (DMRobertson) [reply sync2/handler2/handler.go:384]: They are not mutually exclusive (though I think the question you mean to ask is "are they orthogonal?").

File: sync3/handler/handler.go (hunk 4 above)
Comment (DMRobertson) [reply sync3/handler/handler.go:865]: PTAL at 78b1e59 and 4011e38.

Comment (DMRobertson) [reply sync3/handler/handler.go]: And 9aa8f55 :facepalm:

File: sync2/handler2/handler.go (hunk 2 above)
Comment (DMRobertson) [reply sync2/handler2/handler.go:384]: What I really want is a sum type to be able to express three distinct states:

```
Noop
NewSnapshot(int64 snapID)
ReplacedSnapshot(int64 newSnapID)
```

I'm tempted to leave this as it is tbh.

**Review by kegsay — APPROVED** [review]
Please do not merge this yet. I want to land #367 first as a safe deploy before trying a riskier bigger change.
