### PR TITLE
Reproduce and avoid panic in RemoveHero

### LINKED ISSUE #85: Unexplained panics in `RemoveHero`
Internal sentry links: https://sentry.tools.element.io/organizations/element/issues/69588/?project=56 

```
runtime.errorString: runtime error: invalid memory address or nil pointer dereference
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/conn.go", line 97, in (*Conn).tryRequest.func1
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/internal/roomname.go", line 63, in (*RoomMetadata).RemoveHero
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/handler/connstate.go", line 480, in (*ConnState).getInitialRoomData
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/handler/connstate.go", line 429, in (*ConnState).buildRooms
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/handler/connstate.go", line 157, in (*ConnState).onIncomingRequest
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/handler/connstate.go", line 126, in (*ConnState).OnIncomingRequest
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/conn.go", line 109, in (*Conn).tryRequest
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/conn.go", line 204, in (*Conn).OnIncomingRequest
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/handler/handler.go", line 235, in (*SyncLiveHandler).serve
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/handler/handler.go", line 166, in (*SyncLiveHandler).ServeHTTP
  File "net/http/server.go", line 2109, in HandlerFunc.ServeHTTP
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/v3.go", line 63, in allowCORS.func1
  File "net/http/server.go", line 2109, in HandlerFunc.ServeHTTP
  File "github.com/gorilla/mux@v1.8.0/mux.go", line 210, in (*Router).ServeHTTP
  File "github.com/rs/zerolog@v1.29.0/hlog/hlog.go", line 214, in AccessHandler.func1.1
  File "net/http/server.go", line 2109, in HandlerFunc.ServeHTTP
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/v3.go", line 142, in RunSyncV3Server.func2.1
  File "net/http/server.go", line 2109, in HandlerFunc.ServeHTTP
  File "github.com/rs/zerolog@v1.29.0/hlog/hlog.go", line 29, in NewHandler.func1.1
  File "net/http/server.go", line 2109, in HandlerFunc.ServeHTTP
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/v3.go", line 51, in (*server).ServeHTTP
  File "net/http/server.go", line 2947, in serverHandler.ServeHTTP
  File "net/http/server.go", line 1991, in (*conn).serve
```

https://sentry.tools.element.io/organizations/element/issues/69694/?project=56

```
runtime.errorString: runtime error: invalid memory address or nil pointer dereference
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/conn.go", line 97, in (*Conn).tryRequest.func1
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/internal/roomname.go", line 63, in (*RoomMetadata).RemoveHero
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/handler/connstate.go", line 480, in (*ConnState).getInitialRoomData
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/handler/connstate.go", line 429, in (*ConnState).buildRooms
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/handler/connstate_live.go", line 183, in (*connStateLive).processLiveUpdate
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/handler/connstate_live.go", line 86, in (*connStateLive).liveUpdate
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/handler/connstate.go", line 183, in (*ConnState).onIncomingRequest
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/handler/connstate.go", line 126, in (*ConnState).OnIncomingRequest
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/conn.go", line 109, in (*Conn).tryRequest
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/conn.go", line 204, in (*Conn).OnIncomingRequest
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/handler/handler.go", line 235, in (*SyncLiveHandler).serve
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/handler/handler.go", line 166, in (*SyncLiveHandler).ServeHTTP
  File "net/http/server.go", line 2109, in HandlerFunc.ServeHTTP
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/v3.go", line 63, in allowCORS.func1
  File "net/http/server.go", line 2109, in HandlerFunc.ServeHTTP
  File "github.com/gorilla/mux@v1.8.0/mux.go", line 210, in (*Router).ServeHTTP
  File "github.com/rs/zerolog@v1.29.0/hlog/hlog.go", line 214, in AccessHandler.func1.1
  File "net/http/server.go", line 2109, in HandlerFunc.ServeHTTP
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/v3.go", line 142, in RunSyncV3Server.func2.1
  File "net/http/server.go", line 2109, in HandlerFunc.ServeHTTP
  File "github.com/rs/zerolog@v1.29.0/hlog/hlog.go", line 29, in NewHandler.func1.1
  File "net/http/server.go", line 2109, in HandlerFunc.ServeHTTP
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/v3.go", line 51, in (*server).ServeHTTP
  File "net/http/server.go", line 2947, in serverHandler.ServeHTTP
  File "net/http/server.go", line 1991, in (*conn).serve
```

Both tracebacks start(end?) with

```
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/conn.go", line 97, in (*Conn).tryRequest.func1
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/internal/roomname.go", line 63, in (*RoomMetadata).RemoveHero
  File "github.com/matrix-org/sliding-sync@v0.99.2-0.20230414104506-c6f7516c80c9/sync3/handler/connstate.go", line 480, in (*ConnState).getInitialRoomData
```

which suggests that it is possible for `metadata` to be nil here:

https://github.com/matrix-org/sliding-sync/blob/2e7850edbc095d385e2e5a04a40cc17f273212a2/sync3/handler/connstate.go#L472-L480

### PR DESCRIPTION
**Pull request by DMRobertson**
Intended to fix #85.

Commitwise reviewable.

### CODE REVIEW

File: tests-e2e/client_test.go [hunk 1]
```diff
@@ -199,6 +199,26 @@ func (c *CSAPI) JoinRoom(t *testing.T, roomIDOrAlias string, serverNames []strin
 	return GetJSONFieldStr(t, body, "room_id")
 }
 
+// KnockRoom knocks on the room with the given room ID or alias given, else fails the
+// test. Returns the room ID.
+func (c *CSAPI) KnockRoom(t *testing.T, roomIDOrAlias string, serverNames []string) string {
```
Comment (kegsay) [inline tests-e2e/client_test.go:204]: Please remove this if we don't use it.

File: tests-e2e/spaces_test.go [hunk 2]
```diff
@@ -198,3 +198,39 @@ func TestSpacesFilterInvite(t *testing.T) {
...
+	})
+
+	t.Log("Alice creates a room and marks it as a child of the space.")
+	childID := alice.CreateRoom(t, map[string]interface{}{"preset": "public_chat"})
+	childEventID := alice.SetState(t, parentID, "m.space.child", childID, map[string]interface{}{
+		"via": []string{"localhost"},
+	})
+
+	t.Log("Bob syncs until he sees the m.space.child event in the space.")
+	res = bob.SlidingSyncUntilEventID(t, res.Pos, parentID, childEventID)
```
Comment (kegsay) [inline tests-e2e/spaces_test.go:235]: Needs comments to explain what happens if this bug wasn't fixed. It 500s?
